//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1173.0 using the following command:
// XmlSchemaClassGenerator.Console -o output -p DigitalPreservation.XmlGen --nullable --netCore --interface- https://www.loc.gov/standards/mods/v3/mods-3-8.xsd
namespace DigitalPreservation.XmlGen.Xlink
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("show", Namespace="http://www.w3.org/1999/xlink", AnonymousType=true)]
    public enum Show
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("new")]
        New,
        
        [System.Xml.Serialization.XmlEnumAttribute("replace")]
        Replace,
        
        [System.Xml.Serialization.XmlEnumAttribute("embed")]
        Embed,
        
        [System.Xml.Serialization.XmlEnumAttribute("other")]
        Other,
        
        [System.Xml.Serialization.XmlEnumAttribute("none")]
        None,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("actuate", Namespace="http://www.w3.org/1999/xlink", AnonymousType=true)]
    public enum Actuate
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("onLoad")]
        OnLoad,
        
        [System.Xml.Serialization.XmlEnumAttribute("onRequest")]
        OnRequest,
        
        [System.Xml.Serialization.XmlEnumAttribute("other")]
        Other,
        
        [System.Xml.Serialization.XmlEnumAttribute("none")]
        None,
    }
}
