//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1173.0 using the following command:
// XmlSchemaClassGenerator.Console -o output -p DigitalPreservation.XmlGen --nullable --netCore --interface- https://dublincore.org/schemas/xmls/qdc/2008/02/11/dcterms.xsd
namespace DigitalPreservation.XmlGen.Dc.Terms
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LCSH", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Lcsh : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MESH", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Mesh : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DDC", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ddc : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LCC", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Lcc : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("UDC", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Udc : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Period", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Period : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("W3CDTF", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class W3Cdtf : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DCMIType", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("DCMIType", Namespace="http://purl.org/dc/terms/")]
    public partial class DcmiType : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IMT", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Imt : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("URI", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Uri : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ISO639-2", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Iso6392 : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ISO639-3", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Iso6393 : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RFC1766", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Rfc1766 : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RFC3066", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Rfc3066 : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RFC4646", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Rfc4646 : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Point", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Point : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ISO3166", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Iso3166 : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Box", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Box : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TGN", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Tgn : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    /// <summary>
    /// <para xml:lang="en">This is included as a convenience for schema authors who need to define a root
    ///    		or container element for all of the DC elements and element refinements.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("This is included as a convenience for schema authors who need to define a root or" +
        " container element for all of the DC elements and element refinements.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("elementOrRefinementContainer", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElementOrRefinementContainer
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral> _any;
        
        [System.Xml.Serialization.XmlElementAttribute("title", Type=typeof(DigitalPreservation.XmlGen.Dc.Elements.Title), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("title", Type=typeof(Title), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("alternative", Type=typeof(Alternative), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("creator", Type=typeof(DigitalPreservation.XmlGen.Dc.Elements.Creator), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("creator", Type=typeof(Creator), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("subject", Type=typeof(DigitalPreservation.XmlGen.Dc.Elements.Subject), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("subject", Type=typeof(Subject), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("description", Type=typeof(DigitalPreservation.XmlGen.Dc.Elements.Description), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("description", Type=typeof(Description), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("tableOfContents", Type=typeof(TableOfContents), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("abstract", Type=typeof(Abstract), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("publisher", Type=typeof(DigitalPreservation.XmlGen.Dc.Elements.Publisher), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("publisher", Type=typeof(Publisher), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("contributor", Type=typeof(DigitalPreservation.XmlGen.Dc.Elements.Contributor), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("contributor", Type=typeof(Contributor), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("date", Type=typeof(DigitalPreservation.XmlGen.Dc.Elements.Date), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("date", Type=typeof(Date), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("created", Type=typeof(Created), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("valid", Type=typeof(Valid), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("available", Type=typeof(Available), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("issued", Type=typeof(Issued), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("modified", Type=typeof(Modified), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("dateAccepted", Type=typeof(DateAccepted), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("dateCopyrighted", Type=typeof(DateCopyrighted), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("dateSubmitted", Type=typeof(DateSubmitted), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("type", Type=typeof(DigitalPreservation.XmlGen.Dc.Elements.Type), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("type", Type=typeof(Type), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("format", Type=typeof(DigitalPreservation.XmlGen.Dc.Elements.Format), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("format", Type=typeof(Format), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("extent", Type=typeof(Extent), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("medium", Type=typeof(Medium), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("identifier", Type=typeof(DigitalPreservation.XmlGen.Dc.Elements.Identifier), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("identifier", Type=typeof(Identifier), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("bibliographicCitation", Type=typeof(BibliographicCitation), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("source", Type=typeof(DigitalPreservation.XmlGen.Dc.Elements.Source), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("source", Type=typeof(Source), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("language", Type=typeof(DigitalPreservation.XmlGen.Dc.Elements.Language), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("language", Type=typeof(Language), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("relation", Type=typeof(DigitalPreservation.XmlGen.Dc.Elements.Relation), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("relation", Type=typeof(Relation), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isVersionOf", Type=typeof(IsVersionOf), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("hasVersion", Type=typeof(HasVersion), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isReplacedBy", Type=typeof(IsReplacedBy), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("replaces", Type=typeof(Replaces), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isRequiredBy", Type=typeof(IsRequiredBy), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("requires", Type=typeof(Requires), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isPartOf", Type=typeof(IsPartOf), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("hasPart", Type=typeof(HasPart), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isReferencedBy", Type=typeof(IsReferencedBy), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("references", Type=typeof(References), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isFormatOf", Type=typeof(IsFormatOf), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("hasFormat", Type=typeof(HasFormat), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("conformsTo", Type=typeof(ConformsTo), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("coverage", Type=typeof(DigitalPreservation.XmlGen.Dc.Elements.Coverage), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("coverage", Type=typeof(Coverage), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("spatial", Type=typeof(Spatial), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("temporal", Type=typeof(Temporal), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("rights", Type=typeof(DigitalPreservation.XmlGen.Dc.Elements.Rights), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("rights", Type=typeof(Rights), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("accessRights", Type=typeof(AccessRights), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("license", Type=typeof(License), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("audience", Type=typeof(Audience), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("mediator", Type=typeof(Mediator), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("educationLevel", Type=typeof(EducationLevel), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("accrualMethod", Type=typeof(AccrualMethod), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("accrualPeriodicity", Type=typeof(AccrualPeriodicity), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("accrualPolicy", Type=typeof(AccrualPolicy), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("instructionalMethod", Type=typeof(InstructionalMethod), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("provenance", Type=typeof(Provenance), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("rightsHolder", Type=typeof(RightsHolder), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("any", Namespace="http://purl.org/dc/elements/1.1/")]
        public System.Collections.ObjectModel.Collection<DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ElementOrRefinementContainer" /> class.</para>
        /// </summary>
        public ElementOrRefinementContainer()
        {
            this._any = new System.Collections.ObjectModel.Collection<DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("title", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("title", Namespace="http://purl.org/dc/terms/")]
    public partial class Title : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("creator", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("creator", Namespace="http://purl.org/dc/terms/")]
    public partial class Creator : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("subject", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("subject", Namespace="http://purl.org/dc/terms/")]
    public partial class Subject : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("description", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("description", Namespace="http://purl.org/dc/terms/")]
    public partial class Description : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("publisher", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("publisher", Namespace="http://purl.org/dc/terms/")]
    public partial class Publisher : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("contributor", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("contributor", Namespace="http://purl.org/dc/terms/")]
    public partial class Contributor : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("date", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("date", Namespace="http://purl.org/dc/terms/")]
    public partial class Date : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("type", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("type", Namespace="http://purl.org/dc/terms/")]
    public partial class Type : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("format", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("format", Namespace="http://purl.org/dc/terms/")]
    public partial class Format : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("identifier", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("identifier", Namespace="http://purl.org/dc/terms/")]
    public partial class Identifier : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("source", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("source", Namespace="http://purl.org/dc/terms/")]
    public partial class Source : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("language", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("language", Namespace="http://purl.org/dc/terms/")]
    public partial class Language : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("relation", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("relation", Namespace="http://purl.org/dc/terms/")]
    public partial class Relation : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("coverage", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("coverage", Namespace="http://purl.org/dc/terms/")]
    public partial class Coverage : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("rights", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("rights", Namespace="http://purl.org/dc/terms/")]
    public partial class Rights : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("alternative", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("alternative", Namespace="http://purl.org/dc/terms/")]
    public partial class Alternative : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tableOfContents", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("tableOfContents", Namespace="http://purl.org/dc/terms/")]
    public partial class TableOfContents : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("abstract", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("abstract", Namespace="http://purl.org/dc/terms/")]
    public partial class Abstract : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("created", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("created", Namespace="http://purl.org/dc/terms/")]
    public partial class Created : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("valid", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("valid", Namespace="http://purl.org/dc/terms/")]
    public partial class Valid : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("available", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("available", Namespace="http://purl.org/dc/terms/")]
    public partial class Available : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("issued", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("issued", Namespace="http://purl.org/dc/terms/")]
    public partial class Issued : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("modified", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("modified", Namespace="http://purl.org/dc/terms/")]
    public partial class Modified : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("dateAccepted", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("dateAccepted", Namespace="http://purl.org/dc/terms/")]
    public partial class DateAccepted : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("dateCopyrighted", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("dateCopyrighted", Namespace="http://purl.org/dc/terms/")]
    public partial class DateCopyrighted : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("dateSubmitted", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("dateSubmitted", Namespace="http://purl.org/dc/terms/")]
    public partial class DateSubmitted : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("extent", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("extent", Namespace="http://purl.org/dc/terms/")]
    public partial class Extent : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("medium", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("medium", Namespace="http://purl.org/dc/terms/")]
    public partial class Medium : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("isVersionOf", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("isVersionOf", Namespace="http://purl.org/dc/terms/")]
    public partial class IsVersionOf : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("hasVersion", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("hasVersion", Namespace="http://purl.org/dc/terms/")]
    public partial class HasVersion : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("isReplacedBy", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("isReplacedBy", Namespace="http://purl.org/dc/terms/")]
    public partial class IsReplacedBy : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("replaces", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("replaces", Namespace="http://purl.org/dc/terms/")]
    public partial class Replaces : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("isRequiredBy", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("isRequiredBy", Namespace="http://purl.org/dc/terms/")]
    public partial class IsRequiredBy : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("requires", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("requires", Namespace="http://purl.org/dc/terms/")]
    public partial class Requires : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("isPartOf", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("isPartOf", Namespace="http://purl.org/dc/terms/")]
    public partial class IsPartOf : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("hasPart", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("hasPart", Namespace="http://purl.org/dc/terms/")]
    public partial class HasPart : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("isReferencedBy", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("isReferencedBy", Namespace="http://purl.org/dc/terms/")]
    public partial class IsReferencedBy : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("references", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("references", Namespace="http://purl.org/dc/terms/")]
    public partial class References : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("isFormatOf", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("isFormatOf", Namespace="http://purl.org/dc/terms/")]
    public partial class IsFormatOf : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("hasFormat", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("hasFormat", Namespace="http://purl.org/dc/terms/")]
    public partial class HasFormat : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("conformsTo", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("conformsTo", Namespace="http://purl.org/dc/terms/")]
    public partial class ConformsTo : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("spatial", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("spatial", Namespace="http://purl.org/dc/terms/")]
    public partial class Spatial : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("temporal", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("temporal", Namespace="http://purl.org/dc/terms/")]
    public partial class Temporal : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("audience", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("audience", Namespace="http://purl.org/dc/terms/")]
    public partial class Audience : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("accrualMethod", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("accrualMethod", Namespace="http://purl.org/dc/terms/")]
    public partial class AccrualMethod : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("accrualPeriodicity", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("accrualPeriodicity", Namespace="http://purl.org/dc/terms/")]
    public partial class AccrualPeriodicity : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("accrualPolicy", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("accrualPolicy", Namespace="http://purl.org/dc/terms/")]
    public partial class AccrualPolicy : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("instructionalMethod", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("instructionalMethod", Namespace="http://purl.org/dc/terms/")]
    public partial class InstructionalMethod : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("provenance", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("provenance", Namespace="http://purl.org/dc/terms/")]
    public partial class Provenance : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("rightsHolder", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("rightsHolder", Namespace="http://purl.org/dc/terms/")]
    public partial class RightsHolder : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("mediator", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("mediator", Namespace="http://purl.org/dc/terms/")]
    public partial class Mediator : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("educationLevel", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("educationLevel", Namespace="http://purl.org/dc/terms/")]
    public partial class EducationLevel : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("accessRights", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("accessRights", Namespace="http://purl.org/dc/terms/")]
    public partial class AccessRights : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("license", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("license", Namespace="http://purl.org/dc/terms/")]
    public partial class License : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("bibliographicCitation", Namespace="http://purl.org/dc/terms/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("bibliographicCitation", Namespace="http://purl.org/dc/terms/")]
    public partial class BibliographicCitation : DigitalPreservation.XmlGen.Dc.Elements.SimpleLiteral
    {
    }
}
