name: ECS Restart Service
description: Composite GitHub Action to pull GHCR image, retag and push to ECR and bounce ECS service

permissions:
  id-token: write  # required for OIDC / AWS
  contents: read   # This is required for actions/checkout

inputs:
  target_ecs_service:
    description: "Name of the ECS service to restart"
    required: true
  target_ecs_cluster:
    description: "Name of the ECS cluster running services"
    required: true
  wait_for_services:
    description: "If true, build will wait for ECS service to report as healthy"
    required: true
  role_arn:
    description: "AWS role arn to assume"
    required: true

runs:
  using: "composite"
  steps:
    - id: checkout
      uses: actions/checkout@v4

    - id: configure-aws-creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role_arn }}
        aws-region: eu-west-1

    - id: restart-service
      shell: bash
      env:
        ECS_SERVICE: ${{ inputs.target_ecs_service }}
        ECS_CLUSTER: ${{ inputs.target_ecs_cluster }}
      run: |
        export IFS=","
        for svc in $ECS_SERVICE; do
          aws ecs update-service --force-new-deployment --cluster $ECS_CLUSTER --service $svc
        done

    - id: wait-service
      if: ${{ inputs.wait_for_services == 'true' }}
      shell: bash
      env:
        ECS_SERVICE: ${{ inputs.target_ecs_service }}
        ECS_CLUSTER: ${{ inputs.target_ecs_cluster }}
      run: |
        export IFS=","
        for svc in $ECS_SERVICE; do
          aws ecs wait services-stable --cluster $ECS_CLUSTER --service $svc
        done