FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["src/DigitalPreservation/DigitalPreservation.UI/DigitalPreservation.UI.csproj", "DigitalPreservation.UI/"]
COPY ["src/DigitalPreservation/DigitalPreservation.Core/DigitalPreservation.Core.csproj", "DigitalPreservation.Core/"]
COPY ["src/DigitalPreservation/Preservation.Client/Preservation.Client.csproj", "Preservation.Client/"]

RUN dotnet restore "DigitalPreservation.UI/DigitalPreservation.UI.csproj"

COPY src/DigitalPreservation/ .
WORKDIR "/src/DigitalPreservation.UI"
RUN dotnet build "DigitalPreservation.UI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DigitalPreservation.UI.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

LABEL org.opencontainers.image.source=https://github.com/uol-dlip/digital-preservation
LABEL org.opencontainers.image.description="UoL DLIP Digital Preservation UI"

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DigitalPreservation.UI.dll"]