<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.102.1" />
      <PackageReference Include="AWSSDK.S3" Version="4.0.104.1" />
      <PackageReference Include="AWSSDK.SQS" Version="4.0.100.15" />
      <PackageReference Include="AWSSDK.SSO" Version="4.0.100.17" />
      <PackageReference Include="AWSSDK.SSOOIDC" Version="4.0.100.16" />
      <PackageReference Include="MediatR" Version="12.5.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="MimeTypes" Version="2.5.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DigitalPreservation.Common.Model\DigitalPreservation.Common.Model.csproj" />
      <ProjectReference Include="..\DigitalPreservation.Mets\DigitalPreservation.Mets.csproj" />
      <ProjectReference Include="..\DigitalPreservation.XmlGen\DigitalPreservation.XmlGen.csproj" />
    </ItemGroup>

</Project>
