using System.Xml.Linq;
using DigitalPreservation.Common.Model;
using DigitalPreservation.Common.Model.Mets;
using DigitalPreservation.Common.Model.Transit;
using DigitalPreservation.Common.Model.Transit.Extensions.Metadata;
using FluentAssertions;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Storage.Repository.Common.Mets;
using Storage.Repository.Common.Mets.StorageImpl;

namespace XmlGen.Tests;

/// <summary>
/// Tests that load pre-generated fixture METS files from the Samples directory and
/// verify that MetsManager and MetsParser behave correctly when editing and parsing
/// METS files that already contain paths with spaces, ampersands, and Unicode
/// characters.
///
/// These tests exercise a different scenario than MetsManagerPathTests: instead of
/// generating a fresh METS in each test, they load a persisted METS that was
/// generated by the same code and committed to the repo. This validates that:
///
///   - Saved METS files with special-char IDs round-trip correctly through the
///     full write-to-disk/read-from-disk cycle.
///   - MetsManager can navigate the existing XML structure (via PHYS_* Div IDs)
///     to add, update, and delete entries whose paths contain special characters.
///   - MetsParser produces the correct WorkingFile properties for every entry.
///
/// Each test copies its fixture from Samples/ to Outputs/ before making any edits,
/// so the committed Samples files are never modified by test runs.
///
/// Fixture files in this class:
///   Samples/path-fixture-spaces.xml  — paths with spaces (single and multiple)
///   Samples/path-fixture-special.xml — paths with ampersand and Unicode characters
///
/// To regenerate the fixtures (e.g. after changing MetsManager's output format),
/// run the Generate_Path_Special_Chars_Fixtures test (Category=Manual), then copy
/// the outputs from bin/Debug/net8.0/Outputs/ to Samples/.
/// </summary>
public class MetsManagerPathFixtureTests
{
    private readonly MetsManager metsManager;
    private readonly MetsParser parser;

    private static readonly XNamespace MetsNs = "http://www.loc.gov/METS/";

    // Digests used when generating the fixtures (must match what is in the fixture files)
    private const string Digest1 = "eb634d64ce8e6be5195174ceaef9ac9e19c37119f3b31618630aa633ccdbf68f";
    private const string Digest2 = "4675c73e6fd66d2ea9a684ec79e4e6559bb4d44a35e8234794b0691472b0385d";
    private const string Digest3 = "315bb3bd2eb2da5ce8b848bb7f09803d8a48e64021c4b6fe074aed9cc591c154";

    // Digest used in update operations (different from fixture digests to prove the update took effect)
    private const string UpdateDigest = "801d4a031510adb61ae11412c1554fbaa769a6b4428225ad87a489f92889f105";

    public MetsManagerPathFixtureTests()
    {
        var serviceProvider = new ServiceCollection()
            .AddLogging()
            .BuildServiceProvider();

        var factory = serviceProvider.GetService<ILoggerFactory>();
        var parserLogger = factory!.CreateLogger<MetsParser>();
        var metsLoader = new FileSystemMetsLoader();
        parser = new MetsParser(metsLoader, parserLogger);
        var metsStorage = new FileSystemMetsStorage(parser);
        var premisManager = new PremisManager();
        var premisManagerExif = new PremisManagerExif();
        var premisEventManager = new PremisEventManagerVirus();
        var metadataManager = new MetadataManager(premisManager, premisManagerExif, premisEventManager);
        metsManager = new MetsManager(parser, metsStorage, metadataManager);
    }

    // -----------------------------------------------------------------------
    // Fixture generator
    // Run with: dotnet test --filter "Category=Manual&FullyQualifiedName~Generate_Path_Special_Chars_Fixtures"
    // Then copy Outputs/path-fixture-spaces.xml and Outputs/path-fixture-special.xml
    // into Samples/ and add them to XmlGen.Tests.csproj.
    // -----------------------------------------------------------------------

    [Fact, Trait("Category", "Manual")]
    public async Task Generate_Path_Special_Chars_Fixtures()
    {
        await GenerateSpacesFixture("Outputs/path-fixture-spaces.xml");
        await GenerateSpecialFixture("Outputs/path-fixture-special.xml");
    }

    private async Task GenerateSpacesFixture(string outputPath)
    {
        var uri = new Uri(new FileInfo(outputPath).FullName);
        var createResult = await metsManager.CreateStandardMets(uri, "Spaces Test Fixture");
        createResult.Success.Should().BeTrue();
        var eTag = createResult.Value!.ETag!;

        // A file directly in objects/ with a single space in the name
        var file1 = new WorkingFile
        {
            LocalPath = "objects/my file.pdf",
            Name = "my file.pdf",
            ContentType = "application/pdf",
            Digest = Digest1,
            Size = 54321,
            Modified = new DateTime(2026, 1, 10, 9, 0, 0, DateTimeKind.Utc)
        };
        eTag = await DoAddFile(uri, file1, eTag);

        // A file with multiple spaces in the name
        var file2 = new WorkingFile
        {
            LocalPath = "objects/my great file.pdf",
            Name = "my great file.pdf",
            ContentType = "application/pdf",
            Digest = Digest2,
            Size = 12345,
            Modified = new DateTime(2026, 1, 11, 9, 0, 0, DateTimeKind.Utc)
        };
        eTag = await DoAddFile(uri, file2, eTag);

        // A subdirectory with a space in the name
        var dir = new WorkingDirectory
        {
            LocalPath = "objects/my folder",
            Name = "my folder",
            Modified = new DateTime(2026, 1, 12, 9, 0, 0, DateTimeKind.Utc)
        };
        eTag = await DoAddDirectory(uri, dir, eTag);

        // A file inside the spaced directory, itself with a space in the name
        var file3 = new WorkingFile
        {
            LocalPath = "objects/my folder/my document.pdf",
            Name = "my document.pdf",
            ContentType = "application/pdf",
            Digest = Digest3,
            Size = 99999,
            Modified = new DateTime(2026, 1, 13, 9, 0, 0, DateTimeKind.Utc)
        };
        await DoAddFile(uri, file3, eTag);
    }

    private async Task GenerateSpecialFixture(string outputPath)
    {
        var uri = new Uri(new FileInfo(outputPath).FullName);
        var createResult = await metsManager.CreateStandardMets(uri, "Special Chars Test Fixture");
        createResult.Success.Should().BeTrue();
        var eTag = createResult.Value!.ETag!;

        // A file with Unicode (accented) characters in the name
        var file1 = new WorkingFile
        {
            LocalPath = "objects/résumé.pdf",
            Name = "résumé.pdf",
            ContentType = "application/pdf",
            Digest = Digest1,
            Size = 11111,
            Modified = new DateTime(2026, 1, 10, 9, 0, 0, DateTimeKind.Utc)
        };
        eTag = await DoAddFile(uri, file1, eTag);

        // A file with an ampersand in the name (XML entity-encoding: & → &amp;)
        var file2 = new WorkingFile
        {
            LocalPath = "objects/AT&T guide.pdf",
            Name = "AT&T guide.pdf",
            ContentType = "application/pdf",
            Digest = Digest2,
            Size = 22222,
            Modified = new DateTime(2026, 1, 11, 9, 0, 0, DateTimeKind.Utc)
        };
        await DoAddFile(uri, file2, eTag);
    }

    // Internal helpers used by the generator (assert-free — generator should fail loudly)
    private async Task<string> DoAddFile(Uri metsUri, WorkingFile file, string eTag)
    {
        var result = await metsManager.HandleSingleFileUpload(metsUri, file, eTag);
        result.Success.Should().BeTrue(result.ErrorMessage ?? "");
        var parsed = await parser.GetMetsFileWrapper(metsUri);
        return parsed.Value!.ETag!;
    }

    private async Task<string> DoAddDirectory(Uri metsUri, WorkingDirectory dir, string eTag)
    {
        var result = await metsManager.HandleCreateFolder(metsUri, dir, eTag);
        result.Success.Should().BeTrue(result.ErrorMessage ?? "");
        var parsed = await parser.GetMetsFileWrapper(metsUri);
        return parsed.Value!.ETag!;
    }

    // -----------------------------------------------------------------------
    // Helpers for fixture tests
    // -----------------------------------------------------------------------

    /// <summary>
    /// Copies a fixture from Samples to Outputs so the test can modify it
    /// without touching the committed file. Returns the URI to the copy.
    /// </summary>
    private static Uri CopyFixture(string fixtureName, string outputName)
    {
        var source = new FileInfo($"Samples/{fixtureName}");
        var dest = new FileInfo($"Outputs/{outputName}");
        File.Copy(source.FullName, dest.FullName, overwrite: true);
        return new Uri(dest.FullName);
    }

    /// <summary>
    /// Loads the ETag from the METS at the given URI (without passing an ETag to match,
    /// so it always succeeds regardless of current file content).
    /// </summary>
    private async Task<string> GetETag(Uri metsUri)
    {
        var result = await parser.GetMetsFileWrapper(metsUri);
        result.Success.Should().BeTrue();
        return result.Value!.ETag!;
    }

    // -----------------------------------------------------------------------
    // SPACES FIXTURE — parser tests
    // -----------------------------------------------------------------------

    [Fact]
    public async Task MetsParser_Reads_Spaces_Fixture_Correctly()
    {
        // The parser must correctly populate LocalPath, Name, Digest, and Size
        // for every entry in the fixture, even though the METS ID attributes contain
        // spaces and are technically not valid XML NCNames.

        var metsUri = CopyFixture("path-fixture-spaces.xml", "fixture-spaces-parse.xml");
        var result = await parser.GetMetsFileWrapper(metsUri);

        result.Success.Should().BeTrue();
        var wrapper = result.Value!;

        // All four files present (including the METS file itself)
        var objFiles = wrapper.Files.Where(f => f.LocalPath.StartsWith("objects/")).ToList();
        objFiles.Should().HaveCount(3);

        var f1 = wrapper.Files.Single(f => f.LocalPath == "objects/my file.pdf");
        f1.Name.Should().Be("my file.pdf");
        f1.ContentType.Should().Be("application/pdf");
        f1.Digest.Should().Be(Digest1);
        f1.Size.Should().Be(54321);

        var f2 = wrapper.Files.Single(f => f.LocalPath == "objects/my great file.pdf");
        f2.Name.Should().Be("my great file.pdf");
        f2.Digest.Should().Be(Digest2);
        f2.Size.Should().Be(12345);

        var f3 = wrapper.Files.Single(f => f.LocalPath == "objects/my folder/my document.pdf");
        f3.Name.Should().Be("my document.pdf");
        f3.Digest.Should().Be(Digest3);
        f3.Size.Should().Be(99999);

        // Directory structure
        var phys = wrapper.PhysicalStructure!;
        var objDir = phys.Directories.Single(d => d.Name == FolderNames.Objects);
        objDir.Directories.Should().HaveCount(1);

        var myFolder = objDir.Directories.Single();
        myFolder.Name.Should().Be("my folder");
        myFolder.LocalPath.Should().Be("objects/my folder");
        myFolder.Files.Should().HaveCount(1);
        myFolder.Files[0].LocalPath.Should().Be("objects/my folder/my document.pdf");
    }

    [Fact]
    public async Task MetsParser_Reads_Premis_Metadata_From_Spaces_Fixture()
    {
        // MetsParser must populate FileFormatMetadata from PREMIS techMD for files
        // whose ADMID attribute contains spaces and was therefore split into multiple
        // tokens by the XmlSerializer. The parser must still map the split ADMID back
        // to the correct AmdSec element.
        //
        // The fixture files were created without FileFormatMetadata in WorkingFile.Metadata
        // (no pipeline run). MetsParser produces a fallback FileFormatMetadata with
        // PronomKey="UNKNOWN" and Digest from the PREMIS fixity block, but without Size
        // (Size is only populated when a PRONOM key is present). The top-level
        // WorkingFile.Size IS populated from premis:size.

        var metsUri = CopyFixture("path-fixture-spaces.xml", "fixture-spaces-premis.xml");
        var result = await parser.GetMetsFileWrapper(metsUri);
        result.Success.Should().BeTrue();

        // Parser always synthesises a FileFormatMetadata from PREMIS, even without PRONOM info
        var f1 = result.Value!.Files.Single(f => f.LocalPath == "objects/my file.pdf");
        var ffm1 = f1.Metadata.OfType<FileFormatMetadata>().Single();
        ffm1.Source.Should().Be("METS");
        ffm1.PronomKey.Should().Be("UNKNOWN");
        ffm1.Digest.Should().Be(Digest1);
        f1.Size.Should().Be(54321); // top-level, populated from premis:size

        var f2 = result.Value.Files.Single(f => f.LocalPath == "objects/my great file.pdf");
        var ffm2 = f2.Metadata.OfType<FileFormatMetadata>().Single();
        ffm2.Digest.Should().Be(Digest2);
        f2.Size.Should().Be(12345);

        var f3 = result.Value.Files.Single(f => f.LocalPath == "objects/my folder/my document.pdf");
        var ffm3 = f3.Metadata.OfType<FileFormatMetadata>().Single();
        ffm3.Digest.Should().Be(Digest3);
        f3.Size.Should().Be(99999);
    }

    // -----------------------------------------------------------------------
    // SPACES FIXTURE — MetsManager edit tests
    // -----------------------------------------------------------------------

    [Fact]
    public async Task Can_Add_File_To_Spaced_Directory_In_Spaces_Fixture()
    {
        // Verifies that MetsManager can navigate to an existing directory whose Div ID
        // contains a space ("PHYS_objects/my folder") and add a new child file.
        // Navigation uses SingleOrDefault(d => d.Id == "PHYS_objects/my folder") in
        // GetMetsElements, which must find the element even though the ID is not a
        // valid XML NCName.

        var metsUri = CopyFixture("path-fixture-spaces.xml", "fixture-spaces-add.xml");
        var eTag = await GetETag(metsUri);

        var newFile = new WorkingFile
        {
            LocalPath = "objects/my folder/new addition.pdf",
            Name = "new addition.pdf",
            ContentType = "application/pdf",
            Digest = UpdateDigest,
            Size = 7777,
            Modified = DateTime.UtcNow
        };

        var addResult = await metsManager.HandleSingleFileUpload(metsUri, newFile, eTag);
        addResult.Success.Should().BeTrue();

        var parsed = await parser.GetMetsFileWrapper(metsUri);
        parsed.Success.Should().BeTrue();

        var myFolder = parsed.Value!.PhysicalStructure!
            .Directories.Single(d => d.Name == FolderNames.Objects)
            .Directories.Single(d => d.Name == "my folder");
        myFolder.Files.Should().HaveCount(2);
        myFolder.Files.Should().Contain(f => f.LocalPath == "objects/my folder/new addition.pdf");
        myFolder.Files.Should().Contain(f => f.LocalPath == "objects/my folder/my document.pdf");
    }

    [Fact]
    public async Task Can_Update_Spaced_File_In_Spaces_Fixture()
    {
        // Verifies that MetsManager can update a file whose path contains a space.
        // The update path calls MetadataManager.GetMetadataXml which reconstructs
        // the ADMID from the split Admid Collection via string.Join(' ', ctx.File.Admid).

        var metsUri = CopyFixture("path-fixture-spaces.xml", "fixture-spaces-update.xml");
        var eTag = await GetETag(metsUri);

        var updatedFile = new WorkingFile
        {
            LocalPath = "objects/my file.pdf",
            Name = "my file.pdf",
            ContentType = "application/pdf",
            Digest = UpdateDigest,
            Size = 54321,
            Modified = DateTime.UtcNow,
        };
        updatedFile.Metadata.Add(new FileFormatMetadata
        {
            Source = "Siegfried",
            PronomKey = "fmt/18",
            FormatName = "PDF 1.4",
            Size = 54321,
            Digest = UpdateDigest
        });

        var updateResult = await metsManager.HandleSingleFileUpload(metsUri, updatedFile, eTag);
        updateResult.Success.Should().BeTrue();

        var parsed = await parser.GetMetsFileWrapper(metsUri);
        var file = parsed.Value!.Files.Single(f => f.LocalPath == "objects/my file.pdf");
        var ffm = file.Metadata.OfType<FileFormatMetadata>().Single();
        ffm.PronomKey.Should().Be("fmt/18");
        ffm.Digest.Should().Be(UpdateDigest);
    }

    [Fact]
    public async Task Can_Update_Multi_Spaced_File_In_Spaces_Fixture()
    {
        // Verifies that the ADMID join handles three or more whitespace tokens
        // when updating "my great file.pdf" (ADMID splits into 4 tokens:
        // "ADM_objects/my", "great", "file.pdf").

        var metsUri = CopyFixture("path-fixture-spaces.xml", "fixture-spaces-update-multi.xml");
        var eTag = await GetETag(metsUri);

        var updatedFile = new WorkingFile
        {
            LocalPath = "objects/my great file.pdf",
            Name = "my great file.pdf",
            ContentType = "application/pdf",
            Digest = UpdateDigest,
            Size = 12345,
            Modified = DateTime.UtcNow
        };
        updatedFile.Metadata.Add(new FileFormatMetadata
        {
            Source = "Siegfried",
            PronomKey = "fmt/19",
            FormatName = "PDF 1.5",
            Size = 12345,
            Digest = UpdateDigest
        });

        var updateResult = await metsManager.HandleSingleFileUpload(metsUri, updatedFile, eTag);
        updateResult.Success.Should().BeTrue();

        var parsed = await parser.GetMetsFileWrapper(metsUri);
        var file = parsed.Value!.Files.Single(f => f.LocalPath == "objects/my great file.pdf");
        file.Metadata.OfType<FileFormatMetadata>().Single().PronomKey.Should().Be("fmt/19");
    }

    [Fact]
    public async Task Can_Delete_Spaced_File_In_Spaces_Fixture()
    {
        // Verifies that MetsManager can delete a file whose path contains a space.
        // DeleteFile locates the FileType by Fptr FILEID ("FILE_objects/my file.pdf"),
        // then uses the joined Admid to find and remove the AmdSec.

        var metsUri = CopyFixture("path-fixture-spaces.xml", "fixture-spaces-delete.xml");
        var eTag = await GetETag(metsUri);

        var deleteResult = await metsManager.HandleDeleteObject(metsUri, "objects/my file.pdf", eTag);
        deleteResult.Success.Should().BeTrue();

        var parsed = await parser.GetMetsFileWrapper(metsUri);
        parsed.Value!.Files.Should().NotContain(f => f.LocalPath == "objects/my file.pdf");
        // Other files must remain untouched
        parsed.Value.Files.Should().Contain(f => f.LocalPath == "objects/my great file.pdf");
        parsed.Value.Files.Should().Contain(f => f.LocalPath == "objects/my folder/my document.pdf");
    }

    [Fact]
    public async Task Can_Delete_Spaced_Directory_In_Spaces_Fixture()
    {
        // Verifies that MetsManager can delete an empty directory whose Div ID
        // contains a space. First removes the child file, then removes the directory.

        var metsUri = CopyFixture("path-fixture-spaces.xml", "fixture-spaces-delete-dir.xml");
        var eTag = await GetETag(metsUri);

        // Remove the child first (directory must be empty before deletion)
        var deleteChild = await metsManager.HandleDeleteObject(
            metsUri, "objects/my folder/my document.pdf", eTag);
        deleteChild.Success.Should().BeTrue();

        eTag = await GetETag(metsUri);
        var deleteDir = await metsManager.HandleDeleteObject(metsUri, "objects/my folder", eTag);
        deleteDir.Success.Should().BeTrue();

        var parsed = await parser.GetMetsFileWrapper(metsUri);
        var objDir = parsed.Value!.PhysicalStructure!.Directories.Single(d => d.Name == FolderNames.Objects);
        objDir.Directories.Should().BeEmpty();
    }

    [Fact]
    public async Task Raw_XML_In_Spaces_Fixture_Has_Consistent_IDs()
    {
        // Verifies that the committed fixture file has consistent cross-references
        // between its ID, ADMID, FILEID, and AmdSec/TechMD ID attributes.
        // This is a static check — no MetsManager editing involved.

        var metsUri = CopyFixture("path-fixture-spaces.xml", "fixture-spaces-rawxml.xml");
        var doc = XDocument.Load(metsUri.LocalPath);

        // "my file.pdf": single space splits ADMID into two tokens
        var fileEl = doc.Descendants(MetsNs + "file")
            .Single(f => (string)f.Attribute("ID")! == "FILE_objects/my file.pdf");
        fileEl.Attribute("ADMID")!.Value.Should().Be("ADM_objects/my file.pdf");
        doc.Descendants(MetsNs + "amdSec")
            .Should().Contain(a => (string?)a.Attribute("ID") == "ADM_objects/my file.pdf");

        // "my great file.pdf": three spaces give four tokens
        var fileEl2 = doc.Descendants(MetsNs + "file")
            .Single(f => (string)f.Attribute("ID")! == "FILE_objects/my great file.pdf");
        fileEl2.Attribute("ADMID")!.Value.Should().Be("ADM_objects/my great file.pdf");
        doc.Descendants(MetsNs + "amdSec")
            .Should().Contain(a => (string?)a.Attribute("ID") == "ADM_objects/my great file.pdf");

        // "my folder" directory: Div ID and ADMID
        var dirDiv = doc.Descendants(MetsNs + "div")
            .Single(d => (string?)d.Attribute("ID") == "PHYS_objects/my folder");
        dirDiv.Attribute("ADMID")!.Value.Should().Be("ADM_objects/my folder");

        // "my folder/my document.pdf": combined spaces in directory and filename
        var fileEl3 = doc.Descendants(MetsNs + "file")
            .Single(f => (string)f.Attribute("ID")! == "FILE_objects/my folder/my document.pdf");
        fileEl3.Attribute("ADMID")!.Value.Should().Be("ADM_objects/my folder/my document.pdf");
    }

    // -----------------------------------------------------------------------
    // SPECIAL CHARS FIXTURE — parser tests
    // -----------------------------------------------------------------------

    [Fact]
    public async Task MetsParser_Reads_Special_Chars_Fixture_Correctly()
    {
        var metsUri = CopyFixture("path-fixture-special.xml", "fixture-special-parse.xml");
        var result = await parser.GetMetsFileWrapper(metsUri);
        result.Success.Should().BeTrue();

        var wrapper = result.Value!;

        var f1 = wrapper.Files.Single(f => f.LocalPath == "objects/résumé.pdf");
        f1.Name.Should().Be("résumé.pdf");
        f1.ContentType.Should().Be("application/pdf");
        f1.Digest.Should().Be(Digest1);
        f1.Size.Should().Be(11111);

        var f2 = wrapper.Files.Single(f => f.LocalPath == "objects/AT&T guide.pdf");
        f2.Name.Should().Be("AT&T guide.pdf");
        f2.ContentType.Should().Be("application/pdf");
        f2.Digest.Should().Be(Digest2);
        f2.Size.Should().Be(22222);
    }

    [Fact]
    public async Task MetsParser_Reads_Premis_Metadata_From_Special_Chars_Fixture()
    {
        // Same note as MetsParser_Reads_Premis_Metadata_From_Spaces_Fixture:
        // Size is on the top-level WorkingFile, not on the fallback FileFormatMetadata.

        var metsUri = CopyFixture("path-fixture-special.xml", "fixture-special-premis.xml");
        var result = await parser.GetMetsFileWrapper(metsUri);
        result.Success.Should().BeTrue();

        var f1 = result.Value!.Files.Single(f => f.LocalPath == "objects/résumé.pdf");
        var ffm1 = f1.Metadata.OfType<FileFormatMetadata>().Single();
        ffm1.Source.Should().Be("METS");
        ffm1.PronomKey.Should().Be("UNKNOWN");
        ffm1.Digest.Should().Be(Digest1);
        f1.Size.Should().Be(11111);

        var f2 = result.Value.Files.Single(f => f.LocalPath == "objects/AT&T guide.pdf");
        var ffm2 = f2.Metadata.OfType<FileFormatMetadata>().Single();
        ffm2.Digest.Should().Be(Digest2);
        f2.Size.Should().Be(22222);
    }

    // -----------------------------------------------------------------------
    // SPECIAL CHARS FIXTURE — MetsManager edit tests
    // -----------------------------------------------------------------------

    [Fact]
    public async Task Can_Update_Unicode_File_In_Special_Chars_Fixture()
    {
        // Verifies that MetsManager can update a file whose path contains Unicode
        // characters. Unicode chars are valid XML Name characters, so no special
        // handling is needed, but this confirms the full round-trip.

        var metsUri = CopyFixture("path-fixture-special.xml", "fixture-special-update-unicode.xml");
        var eTag = await GetETag(metsUri);

        var updatedFile = new WorkingFile
        {
            LocalPath = "objects/résumé.pdf",
            Name = "résumé.pdf",
            ContentType = "application/pdf",
            Digest = UpdateDigest,
            Size = 11111,
            Modified = DateTime.UtcNow
        };
        updatedFile.Metadata.Add(new FileFormatMetadata
        {
            Source = "Siegfried",
            PronomKey = "fmt/18",
            FormatName = "PDF 1.4",
            Size = 11111,
            Digest = UpdateDigest
        });

        var updateResult = await metsManager.HandleSingleFileUpload(metsUri, updatedFile, eTag);
        updateResult.Success.Should().BeTrue();

        var parsed = await parser.GetMetsFileWrapper(metsUri);
        var file = parsed.Value!.Files.Single(f => f.LocalPath == "objects/résumé.pdf");
        var ffm = file.Metadata.OfType<FileFormatMetadata>().Single();
        ffm.PronomKey.Should().Be("fmt/18");
        ffm.Digest.Should().Be(UpdateDigest);
    }

    [Fact]
    public async Task Can_Update_Ampersand_File_In_Special_Chars_Fixture()
    {
        // Verifies that MetsManager can update a file whose path contains an ampersand.
        // The XmlSerializer entity-encodes & as &amp; in the XML attribute values.
        // On read, the XmlSerializer decodes &amp; back to &, so the in-memory
        // path strings remain unchanged and navigation works correctly.

        var metsUri = CopyFixture("path-fixture-special.xml", "fixture-special-update-ampersand.xml");
        var eTag = await GetETag(metsUri);

        var updatedFile = new WorkingFile
        {
            LocalPath = "objects/AT&T guide.pdf",
            Name = "AT&T guide.pdf",
            ContentType = "application/pdf",
            Digest = UpdateDigest,
            Size = 22222,
            Modified = DateTime.UtcNow
        };
        updatedFile.Metadata.Add(new FileFormatMetadata
        {
            Source = "Siegfried",
            PronomKey = "fmt/276",
            FormatName = "PDF/A 1a",
            Size = 22222,
            Digest = UpdateDigest
        });

        var updateResult = await metsManager.HandleSingleFileUpload(metsUri, updatedFile, eTag);
        updateResult.Success.Should().BeTrue();

        var parsed = await parser.GetMetsFileWrapper(metsUri);
        var file = parsed.Value!.Files.Single(f => f.LocalPath == "objects/AT&T guide.pdf");
        var ffm = file.Metadata.OfType<FileFormatMetadata>().Single();
        ffm.PronomKey.Should().Be("fmt/276");
        ffm.Digest.Should().Be(UpdateDigest);
    }

    [Fact]
    public async Task Can_Delete_Ampersand_File_In_Special_Chars_Fixture()
    {
        var metsUri = CopyFixture("path-fixture-special.xml", "fixture-special-delete.xml");
        var eTag = await GetETag(metsUri);

        var deleteResult = await metsManager.HandleDeleteObject(metsUri, "objects/AT&T guide.pdf", eTag);
        deleteResult.Success.Should().BeTrue();

        var parsed = await parser.GetMetsFileWrapper(metsUri);
        parsed.Value!.Files.Should().NotContain(f => f.LocalPath == "objects/AT&T guide.pdf");
        parsed.Value.Files.Should().Contain(f => f.LocalPath == "objects/résumé.pdf");
    }

    [Fact]
    public async Task Raw_XML_In_Special_Chars_Fixture_Has_Encoded_Ampersand()
    {
        // Verifies that the ampersand in the fixture file's attribute values is
        // correctly entity-encoded as &amp; in the raw XML bytes, which ensures
        // the file is well-formed XML.

        var metsUri = CopyFixture("path-fixture-special.xml", "fixture-special-rawxml.xml");

        // Read as raw text to confirm entity encoding in the file on disk
        var rawXml = await File.ReadAllTextAsync(metsUri.LocalPath);
        rawXml.Should().Contain("AT&amp;T guide.pdf",
            "ampersand in attribute values must be entity-encoded in well-formed XML");
        rawXml.Should().NotContain("AT&T guide.pdf",
            "a raw unencoded ampersand would make the XML malformed");

        // XDocument decodes &amp; back to & so LINQ-to-XML sees the original string
        var doc = XDocument.Load(metsUri.LocalPath);
        doc.Descendants(MetsNs + "file")
            .Should().Contain(f => (string)f.Attribute("ID")! == "FILE_objects/AT&T guide.pdf");
        doc.Descendants(MetsNs + "amdSec")
            .Should().Contain(a => (string?)a.Attribute("ID") == "ADM_objects/AT&T guide.pdf");
    }
}
