//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1173.0 using the following command:
// XmlSchemaClassGenerator.Console -o output -p DigitalPreservation.XmlGen --nullable --netCore --interface- https://www.loc.gov/standards/mods/v3/mods-3-8.xsd
namespace DigitalPreservation.XmlGen.Xml.Namespace
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("space", Namespace="http://www.w3.org/XML/1998/namespace", AnonymousType=true)]
    public enum Space
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("default")]
        Default,
        
        [System.Xml.Serialization.XmlEnumAttribute("preserve")]
        Preserve,
    }
}
