//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1173.0 using the following command:
// XmlSchemaClassGenerator.Console -o output -p DigitalPreservation.XmlGen --nullable --netCore --interface- https://dublincore.org/schemas/xmls/qdc/2008/02/11/dcterms.xsd
namespace DigitalPreservation.XmlGen.Dc.Dcmitype
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DCMIType", Namespace="http://purl.org/dc/dcmitype/")]
    [System.Xml.Serialization.XmlRootAttribute("DCMIType", Namespace="http://purl.org/dc/dcmitype/")]
    public enum DcmiType
    {
        
        Collection,
        
        Dataset,
        
        Event,
        
        Image,
        
        MovingImage,
        
        StillImage,
        
        InteractiveResource,
        
        Service,
        
        Software,
        
        Sound,
        
        Text,
        
        PhysicalObject,
    }
}
