//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1173.0 using the following command:
// XmlSchemaClassGenerator.Console -o output -p DigitalPreservation.XmlGen --nullable --netCore --interface- https://dublincore.org/schemas/xmls/qdc/2008/02/11/dcterms.xsd
namespace DigitalPreservation.XmlGen.Dc.Elements
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SimpleLiteral", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Abstract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.AccessRights))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.AccrualMethod))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.AccrualPeriodicity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.AccrualPolicy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Alternative))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Any))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Audience))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Available))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.BibliographicCitation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Box))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.ConformsTo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Contributor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Contributor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Coverage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Coverage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Created))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Creator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Creator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Date))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Date))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.DateAccepted))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.DateCopyrighted))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.DateSubmitted))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.DcmiType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Ddc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Description))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Description))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.EducationLevel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Extent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Format))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Format))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.HasFormat))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.HasPart))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.HasVersion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Identifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Identifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Imt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.InstructionalMethod))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.IsFormatOf))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Iso3166))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Iso6392))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Iso6393))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.IsPartOf))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.IsReferencedBy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.IsReplacedBy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.IsRequiredBy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Issued))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.IsVersionOf))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Language))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Language))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Lcc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Lcsh))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.License))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Mediator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Medium))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Mesh))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Modified))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Period))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Point))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Provenance))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Publisher))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Publisher))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.References))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Relation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Relation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Replaces))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Requires))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Rfc1766))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Rfc3066))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Rfc4646))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rights))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Rights))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.RightsHolder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Source))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Source))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Spatial))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Subject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Subject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.TableOfContents))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Temporal))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Tgn))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Title))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Title))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Udc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Uri))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.Valid))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DigitalPreservation.XmlGen.Dc.Terms.W3Cdtf))]
    public partial class SimpleLiteral
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("lang", Namespace="http://www.w3.org/XML/1998/namespace", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Lang { get; set; }
    }
    
    /// <summary>
    /// <para xml:lang="en">This complexType is included as a convenience for schema authors who need to define a root
    ///    		or container element for all of the DC elements.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("This complexType is included as a convenience for schema authors who need to defi" +
        "ne a root or container element for all of the DC elements.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("elementContainer", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElementContainer
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SimpleLiteral> _any;
        
        [System.Xml.Serialization.XmlElementAttribute("title", Type=typeof(Title), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("title", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Title), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("alternative", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Alternative), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("creator", Type=typeof(Creator), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("creator", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Creator), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("subject", Type=typeof(Subject), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("subject", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Subject), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("description", Type=typeof(Description), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("description", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Description), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("tableOfContents", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.TableOfContents), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("abstract", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Abstract), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("publisher", Type=typeof(Publisher), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("publisher", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Publisher), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("contributor", Type=typeof(Contributor), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("contributor", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Contributor), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("date", Type=typeof(Date), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("date", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Date), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("created", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Created), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("valid", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Valid), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("available", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Available), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("issued", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Issued), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("modified", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Modified), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("dateAccepted", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.DateAccepted), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("dateCopyrighted", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.DateCopyrighted), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("dateSubmitted", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.DateSubmitted), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("type", Type=typeof(Type), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("type", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Type), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("format", Type=typeof(Format), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("format", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Format), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("extent", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Extent), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("medium", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Medium), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("identifier", Type=typeof(Identifier), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("identifier", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Identifier), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("bibliographicCitation", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.BibliographicCitation), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("source", Type=typeof(Source), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("source", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Source), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("language", Type=typeof(Language), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("language", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Language), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("relation", Type=typeof(Relation), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("relation", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Relation), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isVersionOf", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.IsVersionOf), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("hasVersion", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.HasVersion), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isReplacedBy", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.IsReplacedBy), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("replaces", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Replaces), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isRequiredBy", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.IsRequiredBy), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("requires", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Requires), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isPartOf", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.IsPartOf), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("hasPart", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.HasPart), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isReferencedBy", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.IsReferencedBy), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("references", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.References), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isFormatOf", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.IsFormatOf), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("hasFormat", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.HasFormat), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("conformsTo", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.ConformsTo), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("coverage", Type=typeof(Coverage), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("coverage", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Coverage), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("spatial", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Spatial), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("temporal", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Temporal), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("rights", Type=typeof(Rights), Namespace="http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("rights", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Rights), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("accessRights", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.AccessRights), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("license", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.License), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("audience", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Audience), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("mediator", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Mediator), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("educationLevel", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.EducationLevel), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("accrualMethod", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.AccrualMethod), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("accrualPeriodicity", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.AccrualPeriodicity), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("accrualPolicy", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.AccrualPolicy), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("instructionalMethod", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.InstructionalMethod), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("provenance", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.Provenance), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("rightsHolder", Type=typeof(DigitalPreservation.XmlGen.Dc.Terms.RightsHolder), Namespace="http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("any")]
        public System.Collections.ObjectModel.Collection<SimpleLiteral> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ElementContainer" /> class.</para>
        /// </summary>
        public ElementContainer()
        {
            this._any = new System.Collections.ObjectModel.Collection<SimpleLiteral>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("title", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("title", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Title : SimpleLiteral
    {
    }
    
    /// <summary>
    /// <para xml:lang="en">This is the default type for all of the DC elements.
    ///            It permits text content only with optional
    ///            xml:lang attribute.
    ///            Text is allowed because mixed="true", but sub-elements
    ///            are disallowed because minOccurs="0" and maxOccurs="0" 
    ///            are on the xs:any tag.
    ///
    ///    	    This complexType allows for restriction or extension permitting
    ///            child elements.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"This is the default type for all of the DC elements. It permits text content only with optional xml:lang attribute. Text is allowed because mixed=""true"", but sub-elements are disallowed because minOccurs=""0"" and maxOccurs=""0"" are on the xs:any tag. This complexType allows for restriction or extension permitting child elements.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("any", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("any", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Any : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("creator", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("creator", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Creator : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("subject", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("subject", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Subject : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("description", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("description", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Description : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("publisher", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("publisher", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Publisher : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("contributor", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("contributor", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Contributor : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("date", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("date", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Date : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("type", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("type", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Type : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("format", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("format", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Format : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("identifier", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("identifier", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Identifier : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("source", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("source", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Source : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("language", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("language", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Language : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("relation", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("relation", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Relation : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("coverage", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("coverage", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Coverage : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1173.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("rights", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("rights", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Rights : SimpleLiteral
    {
    }
}
