// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Preservation.API.Data;

#nullable disable

namespace Preservation.API.Data.Migrations
{
    [DbContext(typeof(PreservationContext))]
    [Migration("20241001154934_Add-Deposit-Fields")]
    partial class AddDepositFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Preservation.API.Data.Entities.Deposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ArchivalGroupPathUnderRoot")
                        .HasColumnType("text")
                        .HasColumnName("archival_group_path_under_root");

                    b.Property<string>("ArchivalGroupProposedName")
                        .HasColumnType("text")
                        .HasColumnName("archival_group_proposed_name");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("Exported")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exported");

                    b.Property<string>("ExportedBy")
                        .HasColumnType("text")
                        .HasColumnName("exported_by");

                    b.Property<string>("Files")
                        .HasColumnType("text")
                        .HasColumnName("files");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("MintedId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("minted_id");

                    b.Property<DateTime?>("Preserved")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preserved");

                    b.Property<string>("PreservedBy")
                        .HasColumnType("text")
                        .HasColumnName("preserved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubmissionText")
                        .HasColumnType("text")
                        .HasColumnName("submission_text");

                    b.Property<string>("VersionExported")
                        .HasColumnType("text")
                        .HasColumnName("version_exported");

                    b.Property<string>("VersionPreserved")
                        .HasColumnType("text")
                        .HasColumnName("version_preserved");

                    b.HasKey("Id")
                        .HasName("pk_deposits");

                    b.ToTable("deposits", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
