namespace Storage.API.Fedora.Model;

public class ConverterOptions
{
    public const string Converter = "Converter";
    
    /// <summary>
    /// The root URI for repository paths
    /// </summary>
    public required Uri RepositoryRoot { get; set; }
    
    /// <summary>
    /// The root URI for people and other API callers
    /// </summary>
    public required Uri AgentRoot { get; set; }
    
    /// <summary>
    /// The path used by the Storage API to import to an archival group
    /// import/archival/group/path
    /// </summary>
    public required Uri ImportRoot { get; set; }
    
    /// <summary>
    /// Use this for JSON responses that need an id, but are not recoverable from that id.
    /// Example - a diff import job generated by the storage API is transient
    /// </summary>
    public required Uri TransientRoot { get; set; }
}