// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Storage.API.Data;

#nullable disable

namespace Storage.API.Data.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20241127174638_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Storage.API.Data.Entities.ImportJob", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArchivalGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("archival_group");

                    b.Property<string>("ImportJobJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("import_job_json");

                    b.Property<string>("ImportJobResultJson")
                        .HasColumnType("text")
                        .HasColumnName("import_job_result_json");

                    b.HasKey("Id")
                        .HasName("pk_import_jobs");

                    b.ToTable("import_jobs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
