// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Storage.API.Data;

#nullable disable

namespace Storage.API.Data.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20250308160757_Add Received, EndTime and ImportJobResultUri to ImportJob DB entity in Storage")]
    partial class AddReceivedEndTimeandImportJobResultUritoImportJobDBentityinStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Storage.API.Data.Entities.Export", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArchivalGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("archival_group");

                    b.Property<DateTime?>("DateBegun")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_begun");

                    b.Property<DateTime?>("DateFinished")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_finished");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("ExportResultJson")
                        .HasColumnType("text")
                        .HasColumnName("export_result_json");

                    b.HasKey("Id")
                        .HasName("pk_export_results");

                    b.ToTable("export_results", (string)null);
                });

            modelBuilder.Entity("Storage.API.Data.Entities.ImportJob", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ArchivalGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("archival_group");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("ImportJobJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("import_job_json");

                    b.Property<string>("ImportJobResultJson")
                        .HasColumnType("text")
                        .HasColumnName("import_job_result_json");

                    b.Property<string>("ImportJobResultUri")
                        .HasColumnType("text")
                        .HasColumnName("import_job_result_uri");

                    b.Property<DateTime?>("Received")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received");

                    b.HasKey("Id")
                        .HasName("pk_import_jobs");

                    b.ToTable("import_jobs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
