using System.Reflection;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Xsl;

namespace DigitalPreservation.Mets.Conformance;

/// <summary>
/// Executes the canonical Schematron tier rules against a METS document.
///
/// The rules are authored once, as Schematron, next to the Python judge
/// (src/mets-editability/schematron/*.sch). .NET has no Schematron processor, so this runs the
/// compiled XSLT form of the same rules (schematron/compiled/*.xsl, regenerated by
/// tools/compile_schematron.py and embedded here), which emits SVRL; each svrl:failed-assert
/// carries the assert's @id - a finding code shared with the native checks and the Python side.
/// </summary>
internal static class SchematronRunner
{
    private static readonly XNamespace Svrl = "http://purl.oclc.org/dsdl/svrl";
    private static readonly Dictionary<string, XslCompiledTransform> Transforms = new();
    private static readonly object TransformsLock = new();

    /// <summary>
    /// Every failed assert of one tier against one mets:mets element, as (code, message) - one
    /// entry per occurrence, so callers can count.
    /// </summary>
    internal static List<(string Code, string Message)> Failures(string tier, XElement mets)
    {
        var transform = TransformFor(tier);
        var report = new XDocument();
        using (var reader = mets.CreateReader())
        using (var writer = report.CreateWriter())
        {
            transform.Transform(reader, writer);
        }

        return report.Descendants(Svrl + "failed-assert")
            .Select(failed => (
                failed.Attribute("id")?.Value ?? "SCHEMATRON",
                string.Join(' ',
                    (failed.Element(Svrl + "text")?.Value ?? "")
                    .Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries))))
            .ToList();
    }

    private static XslCompiledTransform TransformFor(string tier)
    {
        lock (TransformsLock)
        {
            if (Transforms.TryGetValue(tier, out var existing))
            {
                return existing;
            }
            var assembly = Assembly.GetExecutingAssembly();
            var resourceName = assembly.GetManifestResourceNames()
                .Single(name => name.EndsWith($"{tier}.xsl", StringComparison.Ordinal));
            using var stream = assembly.GetManifestResourceStream(resourceName)!;
            using var reader = XmlReader.Create(stream);
            var transform = new XslCompiledTransform();
            transform.Load(reader);
            Transforms[tier] = transform;
            return transform;
        }
    }
}
